# -*- coding: utf-8 -*-
"""CGIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193dxYbse2Md0atRuSTomx2qZGU97IFIW
"""

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path)

# Convert image to RGB (Colab uses RGB, while OpenCV loads in BGR)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Apply Gaussian blur
blurred_image = cv2.GaussianBlur(image_rgb, (15, 15), 0)  # Kernel size (15x15)

# Display original and blurred images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(blurred_image)
plt.title("Gaussian Blurred Image")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path)

# Convert image to RGB (since OpenCV loads in BGR format)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Apply Median filter (kernel size = 5)
median_filtered = cv2.medianBlur(image_rgb, 5)

# Display original and median filtered images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(median_filtered)
plt.title("Median Filtered Image")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale

# Apply Canny edge detection
edges = cv2.Canny(image, 100, 200)  # Thresholds: 100 (low), 200 (high)

# Display original and edge-detected images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(edges, cmap="gray")
plt.title("Canny Edge Detection")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale

# Apply Laplacian filter for second-order edge detection
laplacian = cv2.Laplacian(image, cv2.CV_64F)  # Use 64-bit float output for precision
laplacian = np.uint8(np.absolute(laplacian))  # Convert to unsigned 8-bit

# Display original and Laplacian edge-detected images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(laplacian, cmap="gray")
plt.title("Laplacian Edge Detection")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale

# Apply Binary Thresholding
threshold_value = 127  # Threshold value (can be adjusted)
max_value = 255  # Maximum pixel value
_, binary_thresh = cv2.threshold(image, threshold_value, max_value, cv2.THRESH_BINARY)

# Display original and binary thresholded images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(binary_thresh, cmap="gray")
plt.title("Binary Thresholded Image")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale

# Apply Otsu's Thresholding
_, otsu_thresh = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# Display original and Otsu thresholded images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(otsu_thresh, cmap="gray")
plt.title("Otsu's Thresholding")
plt.axis("off")

plt.show()

from google.colab import files

# Upload an image
uploaded = files.upload()

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the uploaded image
image_path = list(uploaded.keys())[0]  # Get the uploaded file name
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Convert to grayscale

# Apply Otsu's Thresholding for binary image
_, binary_image = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# Define a kernel (structuring element)
kernel = np.ones((3,3), np.uint8)  # 3x3 kernel

# Morphological operations
cleaned_image = cv2.morphologyEx(binary_image, cv2.MORPH_OPEN, kernel)  # Opening: Erosion + Dilation

# Display original and cleaned images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(binary_image, cmap="gray")
plt.title("Binary Image (Before Cleaning)")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(cleaned_image, cmap="gray")
plt.title("Morphologically Cleaned Image")
plt.axis("off")

plt.show()

